# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('caller_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallSessionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='service_development.CallSession')),
            ],
        ),
        migrations.CreateModel(
            name='KasaDakaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_id', models.CharField(max_length=100, verbose_name='phone number')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='Ensure your file is in the correct format! Wave: Sample rate 8KHz, 16 bit, mono, Codec: PCM 16 LE (s16l)', upload_to='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_development.Language')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='date last modified')),
                ('active', models.BooleanField(help_text='This voice service is only accessible for users when marked active.', verbose_name='Voice service active')),
                ('requires_registration', models.BooleanField(verbose_name='Requires user registration')),
                ('supported_languages', models.ManyToManyField(blank=True, to='service_development.Language')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceServiceSubElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='date last modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('voiceservicesubelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceSubElement')),
            ],
            bases=('service_development.voiceservicesubelement',),
        ),
        migrations.CreateModel(
            name='VoiceServiceElement',
            fields=[
                ('voiceservicesubelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceSubElement')),
            ],
            bases=('service_development.voiceservicesubelement',),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='service',
            field=models.ForeignKey(help_text='The service to which this element belongs', on_delete=django.db.models.deletion.CASCADE, to='service_development.VoiceService'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='voicefragment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='eight',
            field=models.ForeignKey(help_text='The number 8', on_delete=django.db.models.deletion.PROTECT, related_name='language_eight', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='error_message',
            field=models.ForeignKey(help_text='A general error message', on_delete=django.db.models.deletion.PROTECT, related_name='language_error_message', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='five',
            field=models.ForeignKey(help_text='The number 5', on_delete=django.db.models.deletion.PROTECT, related_name='language_five', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='four',
            field=models.ForeignKey(help_text='The number 4', on_delete=django.db.models.deletion.PROTECT, related_name='language_four', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='nine',
            field=models.ForeignKey(help_text='The number 9', on_delete=django.db.models.deletion.PROTECT, related_name='language_nine', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='one',
            field=models.ForeignKey(help_text='The number 1', on_delete=django.db.models.deletion.PROTECT, related_name='language_one', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='post_choice_option',
            field=models.ForeignKey(help_text="The fragment that is to be played before a choice option (e.g. 'to select option X, [please press] 1')", on_delete=django.db.models.deletion.PROTECT, related_name='language_post_choice_option', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='pre_choice_option',
            field=models.ForeignKey(help_text="The fragment that is to be played before a choice option (e.g. '[to select] option X, please press 1')", on_delete=django.db.models.deletion.PROTECT, related_name='language_pre_choice_option', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='select_language',
            field=models.ForeignKey(help_text='A message requesting the user to select a language', on_delete=django.db.models.deletion.PROTECT, related_name='language_select_language', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='seven',
            field=models.ForeignKey(help_text='The number 7', on_delete=django.db.models.deletion.PROTECT, related_name='language_seven', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='six',
            field=models.ForeignKey(help_text='The number 6', on_delete=django.db.models.deletion.PROTECT, related_name='language_six', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='three',
            field=models.ForeignKey(help_text='The number 3', on_delete=django.db.models.deletion.PROTECT, related_name='language_three', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='two',
            field=models.ForeignKey(help_text='The number 2', on_delete=django.db.models.deletion.PROTECT, related_name='language_two', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='voice_label',
            field=models.ForeignKey(help_text='A Voice Label of the name of the language', on_delete=django.db.models.deletion.PROTECT, related_name='language_description_voice_label', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='language',
            name='zero',
            field=models.ForeignKey(help_text='The number 0', on_delete=django.db.models.deletion.PROTECT, related_name='language_zero', to='service_development.VoiceLabel'),
        ),
        migrations.AddField(
            model_name='kasadakauser',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.Language'),
        ),
        migrations.AddField(
            model_name='kasadakauser',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_development.VoiceService'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.Language'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.VoiceService'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.KasaDakaUser'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.CreateModel(
            name='MessagePresentation',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('final_element', models.BooleanField(default=False, verbose_name='This element will terminate the call')),
                ('_redirect', models.ForeignKey(blank=True, help_text='The element to redirect to after the message has been played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_messagepresentation_related', to='service_development.VoiceServiceElement')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.AddField(
            model_name='voiceservice',
            name='_start_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_development_voiceservice_related', to='service_development.VoiceServiceElement'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='_redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_choiceoption_redirect_related', to='service_development.VoiceServiceElement'),
        ),
        migrations.AddField(
            model_name='callsessionstep',
            name='_visited_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.VoiceServiceElement'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_options', to='service_development.Choice'),
        ),
    ]
