# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_announce_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announce',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
