# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0003_auto_20170503_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credentials', models.FileField(help_text='Ensure your file is in the correct format! Wave: Sample rate 8KHz, 16 bit, mono, Codec: PCM 16 LE (s16l)', upload_to='')),
                ('Date', models.CharField(max_length=100)),
                ('product', models.FileField(help_text='Ensure your file is in the correct format! Wave: Sample rate 8KHz, 16 bit, mono, Codec: PCM 16 LE (s16l)', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credentials', models.FileField(help_text='Ensure your file is in the correct format! Wave: Sample rate 8KHz, 16 bit, mono, Codec: PCM 16 LE (s16l)', upload_to='')),
                ('Date', models.CharField(max_length=100)),
                ('product', models.FileField(help_text='Ensure your file is in the correct format! Wave: Sample rate 8KHz, 16 bit, mono, Codec: PCM 16 LE (s16l)', upload_to='')),
            ],
        ),
    ]
