# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0004_consumer_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.FileField(help_text=b'Ensure your file is in the correct format! Wave: Sample rate 8KHz, 16 bit, mono, Codec: PCM 16 LE (s16l)', upload_to=b'')),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.FileField(help_text=b'Ensure your file is in the correct format! Wave: Sample rate 8KHz, 16 bit, mono, Codec: PCM 16 LE (s16l)', upload_to=b'')),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('final_element', models.BooleanField(default=False, verbose_name=b'This element will terminate the call')),
                ('_redirect', models.ForeignKey(blank=True, help_text=b'The element to redirect to after the message has been played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_record_related', to='service_development.VoiceServiceElement')),
                ('voice_labelc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.VoiceLabel')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
