# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0005_auto_20170504_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Message',
            field=models.FileField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Message',
            field=models.FileField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='_redirect',
            field=models.ForeignKey(blank=True, help_text='The element to redirect to after the message has been played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_record_related', to='service_development.VoiceServiceElement'),
        ),
        migrations.AlterField(
            model_name='record',
            name='final_element',
            field=models.BooleanField(default=False, verbose_name='This element will terminate the call'),
        ),
    ]
