# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0006_auto_20170505_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voice_label_no_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_input', to='service_development.VoiceLabel'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Message',
            field=models.FileField(upload_to='.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Message',
            field=models.FileField(upload_to='.'),
        ),
    ]
