# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0007_auto_20170506_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_announcement',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('final_element', models.BooleanField(default=False, verbose_name='This element will terminate the call')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.CreateModel(
            name='Record_offer',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('final_element', models.BooleanField(default=False, verbose_name='This element will terminate the call')),
                ('_redirect', models.ForeignKey(blank=True, help_text='The element to redirect to after the message has been played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_record_offer_related', to='service_development.VoiceServiceElement')),
                ('voice_labelc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.VoiceLabel')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.RemoveField(
            model_name='record',
            name='_redirect',
        ),
        migrations.RemoveField(
            model_name='record',
            name='voice_labelc',
        ),
        migrations.RemoveField(
            model_name='record',
            name='voiceserviceelement_ptr',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='record_announcement',
            name='_redirect',
            field=models.ForeignKey(blank=True, help_text='The element to redirect to after the message has been played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_record_announcement_related', to='service_development.VoiceServiceElement'),
        ),
        migrations.AddField(
            model_name='record_announcement',
            name='voice_labelc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.VoiceLabel'),
        ),
    ]
