# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0008_auto_20170506_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_announcement',
            old_name='voice_labelc',
            new_name='voice_label_confirm',
        ),
        migrations.RenameField(
            model_name='record_offer',
            old_name='voice_labelc',
            new_name='voice_label_confirm',
        ),
    ]
